from datetime import datetime

from reportlab.lib.styles import (
    getSampleStyleSheet,
)

from reportlab.platypus import (
    Paragraph,
    Spacer,
)


def add_pdf_footer(
    elements,
):

    styles = (
        getSampleStyleSheet()
    )

    generated_on = (
        datetime.now()
        .strftime(
            "%d-%b-%Y %H:%M"
        )
    )

    elements.append(
        Spacer(1, 12)
    )
    
    elements.append(
        Paragraph(
            """
            <para alignment="center">
            <font color="#909090">
            ________________________________________________
            </font>
            </para>
            """,
            styles["Normal"],
        )
    )
    
    elements.append(
        Paragraph(
            f"""
            <para alignment="center">
            <font size="8" color="#606060">
            This document was generated by
            <b>Fleet Management System</b>
            on {generated_on}
            and is intended for internal use only.
            </font>
            </para>
            """,
            styles["Normal"],
        )
    )