"""baseline_v7_3

Revision ID: e3415241b8bc
Revises: 
Create Date: 2026-07-06 16:56:16.248942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3415241b8bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_master',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=100), nullable=True),
    sa.Column('part_name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('part_id'),
    schema='inventory'
    )
    op.create_table('driver_master',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=200), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('dl_number', sa.String(length=100), nullable=True),
    sa.Column('dl_expiry_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('dl_number'),
    schema='master'
    )
    op.create_table('employee_master',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_type', sa.String(length=30), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    schema='master'
    )
    op.create_table('fuel_type_ref',
    sa.Column('fuel_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('fuel_type_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('fuel_type_id'),
    sa.UniqueConstraint('fuel_type_name'),
    schema='reference'
    )
    op.create_table('maintenance_type_ref',
    sa.Column('maintenance_type_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('maintenance_type_id'),
    sa.UniqueConstraint('maintenance_type_name'),
    schema='reference'
    )
    op.create_table('severity',
    sa.Column('severity_id', sa.SmallInteger(), nullable=False),
    sa.Column('severity_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('severity_id'),
    sa.UniqueConstraint('severity_name'),
    schema='reference'
    )
    op.create_table('vehicle_type_ref',
    sa.Column('vehicle_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('vehicle_type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_type_id'),
    sa.UniqueConstraint('vehicle_type_name'),
    schema='reference'
    )
    op.create_table('stock_transaction',
    sa.Column('stock_txn_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['inventory.part_master.part_id'], ),
    sa.PrimaryKeyConstraint('stock_txn_id'),
    schema='inventory'
    )
    op.create_table('vehicle_master',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('fuel_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('rc_number', sa.String(length=50), nullable=False),
    sa.Column('engine_no', sa.String(length=100), nullable=True),
    sa.Column('chassis_no', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('fuel_capacity', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['reference.fuel_type_ref.fuel_type_id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['reference.vehicle_type_ref.vehicle_type_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('chassis_no'),
    sa.UniqueConstraint('engine_no'),
    sa.UniqueConstraint('rc_number'),
    schema='master'
    )
    op.create_table('part_request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['master.vehicle_master.vehicle_id'], ),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('request_number'),
    schema='inventory'
    )
    op.create_table('vehicle_complaint',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('complaint_date', sa.DateTime(), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('driver_reason', sa.Text(), nullable=True),
    sa.Column('vehicle_received_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['master.driver_master.driver_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['master.vehicle_master.vehicle_id'], ),
    sa.PrimaryKeyConstraint('complaint_id'),
    schema='maintenance'
    )
    op.create_table('driver_vehicle_assignment',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['master.driver_master.driver_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['master.vehicle_master.vehicle_id'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    schema='operations'
    )
    op.create_table('approval_request',
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['master.employee_master.employee_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['inventory.part_request.request_id'], ),
    sa.PrimaryKeyConstraint('approval_id'),
    schema='inventory'
    )
    op.create_table('technician_inspection',
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('observed_issue', sa.Text(), nullable=True),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['maintenance.vehicle_complaint.complaint_id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['master.employee_master.employee_id'], ),
    sa.PrimaryKeyConstraint('inspection_id'),
    schema='maintenance'
    )
    op.create_table('whatsapp_message_log',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('recipient_mobile', sa.String(length=20), nullable=False),
    sa.Column('send_status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['inventory.approval_request.approval_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    schema='integration'
    )
    op.create_table('maintenance_job_card',
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['maintenance.vehicle_complaint.complaint_id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['maintenance.technician_inspection.inspection_id'], ),
    sa.PrimaryKeyConstraint('job_card_id'),
    schema='transact'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_job_card', schema='transact')
    op.drop_table('whatsapp_message_log', schema='integration')
    op.drop_table('technician_inspection', schema='maintenance')
    op.drop_table('approval_request', schema='inventory')
    op.drop_table('driver_vehicle_assignment', schema='operations')
    op.drop_table('vehicle_complaint', schema='maintenance')
    op.drop_table('part_request', schema='inventory')
    op.drop_table('vehicle_master', schema='master')
    op.drop_table('stock_transaction', schema='inventory')
    op.drop_table('vehicle_type_ref', schema='reference')
    op.drop_table('severity', schema='reference')
    op.drop_table('maintenance_type_ref', schema='reference')
    op.drop_table('fuel_type_ref', schema='reference')
    op.drop_table('employee_master', schema='master')
    op.drop_table('driver_master', schema='master')
    op.drop_table('part_master', schema='inventory')
    # ### end Alembic commands ###
