from datetime import datetime

from reportlab.lib import colors

from reportlab.platypus import (
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def add_pdf_footer(
    elements,
    generated_by="Fleet Management System",
):

    elements.append(
        Spacer(1, 40)
    )

    generated_on = (
        datetime.now()
        .strftime(
            "%d-%b-%Y %H:%M"
        )
    )

    footer_data = [

        [
            "Generated By",
            generated_by,
        ],

        [
            "Generated On",
            generated_on,
        ],

        [
            "Document Status",
            "SYSTEM GENERATED",
        ],
    ]

    footer_table = Table(
        footer_data,
        colWidths=[
            140,
            350,
        ],
    )

    footer_table.setStyle(
        TableStyle([

            (
                "GRID",
                (0, 0),
                (-1, -1),
                1,
                colors.black,
            ),

            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.lightgrey,
            ),

            (
                "TEXTCOLOR",
                (1, 2),
                (1, 2),
                colors.darkgreen,
            ),

            (
                "FONTSIZE",
                (0, 0),
                (-1, -1),
                9,
            ),
        ])
    )

    elements.append(
        footer_table
    )